name: Setup ECR Repo and S3 State Bucket

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Execute setup script
      run: python infra/terraform/setup_aws.py
